spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: client.exchange
    logging:
      level:
        org.springframework.amqp: DEBUG
